<a href="https://colab.research.google.com/github/ahmadsofian/GAN-for-Synthetic-Data-Generation/blob/main/Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

file_path = '/content/drive/MyDrive/IoT23 Dataset/IoT23_Dataset.csv'


# Load the dataset into a pandas DataFrame
df = pd.read_csv(file_path)

print("Dataset Loaded Successfully!")
print(f"\nShape of the DataFrame: {df.shape}")

/tmp/ipython-input-648256540.py:7: DtypeWarning: Columns (9,10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

Dataset Loaded Successfully!

Shape of the DataFrame: (1446621, 22)

Re Label The Dataset

In [ ]:
df['label'].value_counts()

label
-   Malicious   PartOfAHorizontalPortScan          578916
(empty)   Malicious   PartOfAHorizontalPortScan    247023
-   Malicious   Okiru                              163016
-   Benign   -                                     146275
-   Malicious   DDoS                               138777
(empty)   Malicious   Okiru                         99674
(empty)   Benign   -                                51534
(empty)   Malicious   C&C                            8229
-   Malicious   C&C                                  6871
(empty)   Malicious   Attack                         3814
-   benign   -                                       1947
-   Malicious   C&C-HeartBeat                         227
(empty)   Malicious   C&C-HeartBeat                   122
-   Malicious   Attack                                101
-   Malicious   C&C-FileDownload                       43
-   Malicious   C&C-Torii                              30
-   Malicious   FileDownload                           13
-   Malicious   C&C-HeartBeat-FileDownload              8
-   Malicious   C&C-Mirai                               1
Name: count, dtype: int64

In [ ]:
df.loc[(df.label == '-   Malicious   PartOfAHorizontalPortScan'), 'label'] = 'PartOfAHorizontalPortScan'
df.loc[(df.label == '(empty)   Malicious   PartOfAHorizontalPortScan'), 'label'] = 'PartOfAHorizontalPortScan'
df.loc[(df.label == '-   Malicious   Okiru'), 'label'] = 'Okiru'
df.loc[(df.label == '(empty)   Malicious   Okiru'), 'label'] = 'Okiru'
df.loc[(df.label == '-   Benign   -'), 'label'] = 'Benign'
df.loc[(df.label == '(empty)   Benign   -'), 'label'] = 'Benign'
df.loc[(df.label == '-   Malicious   DDoS'), 'label'] = 'DDoS'
df.loc[(df.label == '-   Malicious   C&C'), 'label'] = 'C&C'
df.loc[(df.label == '(empty)   Malicious   C&C'), 'label'] = 'C&C'
df.loc[(df.label == '-   Malicious   Attack'), 'label'] = 'Attack'
df.loc[(df.label == '(empty)   Malicious   Attack'), 'label'] = 'Attack'
df.loc[(df.label == '-   Malicious   C&C-HeartBeat'), 'label'] = 'C&C-HeartBeat'
df.loc[(df.label == '(empty)   Malicious   C&C-HeartBeat'), 'label'] = 'C&C-HeartBeat'
df.loc[(df.label == '-   Malicious   C&C-FileDownload'), 'label'] = 'C&C-FileDownload'
df.loc[(df.label == '-   Malicious   C&C-Torii'), 'label'] = 'C&C-Torii'
df.loc[(df.label == '-   Malicious   C&C-HeartBeat-FileDownload'), 'label'] = 'C&C-HeartBeat-FileDownload'
df.loc[(df.label == '-   Malicious   FileDownload'), 'label'] = 'FileDownload'
df.loc[(df.label == '-   Malicious   C&C-Mirai'), 'label'] = 'C&C-Mirai'
df.loc[(df.label == '-   Malicious   Okiru-Attack'), 'label'] = 'Okiru-Attack'
df.loc[(df.label == '-   benign   -'), 'label'] = 'Benign'

In [ ]:
df['label'].value_counts()

label
PartOfAHorizontalPortScan     825939
Okiru                         262690
Benign                        199756
DDoS                          138777
C&C                            15100
Attack                          3915
C&C-HeartBeat                    349
C&C-FileDownload                  43
C&C-Torii                         30
FileDownload                      13
C&C-HeartBeat-FileDownload         8
C&C-Mirai                          1
Name: count, dtype: int64

In [ ]:
df.loc[(df.label == 'C&C-HeartBeat'), 'label'] = 'C&C'
df.loc[(df.label == 'C&C-FileDownload'), 'label'] = 'C&C'
df.loc[(df.label == 'C&C-Torii'), 'label'] = 'C&C'
df.loc[(df.label == 'C&C-HeartBeat-FileDownload'), 'label'] = 'C&C'
df.loc[(df.label == 'C&C-Mirai'), 'label'] = 'C&C'

df['label'].value_counts()

label
PartOfAHorizontalPortScan    825939
Okiru                        262690
Benign                       199756
DDoS                         138777
C&C                           15531
Attack                         3915
FileDownload                     13
Name: count, dtype: int64

In [ ]:
df.shape

(1446621, 22)

In [ ]:
df.head()

,Unnamed: 0,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,...,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,label
0,0,1.525880e+09,CDe43c1PtgynajGI6,192.168.100.103,60905.0,131.174.215.147,23.0,tcp,-,2.998796,...,S0,-,-,0.0,S,3.0,180.0,0.0,0.0,PartOfAHorizontalPortScan
1,1,1.525880e+09,CJaDcG3MZzvf1YVYI4,192.168.100.103,44301.0,91.42.47.63,23.0,tcp,-,-,...,S0,-,-,0.0,S,1.0,60.0,0.0,0.0,PartOfAHorizontalPortScan
2,2,1.525880e+09,CMBrup3BLXivSp4Avc,192.168.100.103,50244.0,120.210.108.200,23.0,tcp,-,-,...,S0,-,-,0.0,S,1.0,60.0,0.0,0.0,PartOfAHorizontalPortScan
3,3,1.525880e+09,CfHl9r3XMYtDQRrHnh,192.168.100.103,34243.0,147.7.65.203,49560.0,tcp,-,2.998804,...,S0,-,-,0.0,S,3.0,180.0,0.0,0.0,Benign
4,4,1.525880e+09,C7USrA15nFVkniMqC5,192.168.100.103,34840.0,145.164.35.6,21288.0,tcp,-,-,...,S0,-,-,0.0,S,1.0,60.0,0.0,0.0,Benign

In [ ]:
print(df.columns)

Index(['Unnamed: 0', 'ts', 'uid', 'id.orig_h', 'id.orig_p', 'id.resp_h',
       'id.resp_p', 'proto', 'service', 'duration', 'orig_bytes', 'resp_bytes',
       'conn_state', 'local_orig', 'local_resp', 'missed_bytes', 'history',
       'orig_pkts', 'orig_ip_bytes', 'resp_pkts', 'resp_ip_bytes', 'label'],
      dtype='object')

In [ ]:
df.to_csv('IoT23Raw.csv',index=False)

Handle Missing Value

In [ ]:
#Show count of NA in each features
print(df.isna().sum())

Unnamed: 0       0
ts               0
uid              0
id.orig_h        0
id.orig_p        0
id.resp_h        0
id.resp_p        0
proto            0
service          0
duration         0
orig_bytes       0
resp_bytes       0
conn_state       0
local_orig       0
local_resp       0
missed_bytes     0
history          0
orig_pkts        0
orig_ip_bytes    0
resp_pkts        0
resp_ip_bytes    0
label            0
dtype: int64

In [ ]:
for column in df.columns:
    if df[column].dtype == 'object':
        count = (df[column] == '-').sum()
        if count > 0:
            print(f"Column '{column}': {count} occurrences of '-'")

import numpy as np

print("Total NaN before replacing:")
print(df.isna().sum())
print()

# Replace '-' with NaN
df.replace(['-'], np.nan, inplace=True)

print("Total NaN after replacing '-':")
print(df.isna().sum())

Column 'service': 1434755 occurrences of '-'
Column 'duration': 900411 occurrences of '-'
Column 'orig_bytes': 900411 occurrences of '-'
Column 'resp_bytes': 900411 occurrences of '-'
Column 'local_orig': 1446621 occurrences of '-'
Column 'local_resp': 1446621 occurrences of '-'
Column 'history': 3786 occurrences of '-'
Total NaN before replacing:
Unnamed: 0       0
ts               0
uid              0
id.orig_h        0
id.orig_p        0
id.resp_h        0
id.resp_p        0
proto            0
service          0
duration         0
orig_bytes       0
resp_bytes       0
conn_state       0
local_orig       0
local_resp       0
missed_bytes     0
history          0
orig_pkts        0
orig_ip_bytes    0
resp_pkts        0
resp_ip_bytes    0
label            0
dtype: int64

/tmp/ipython-input-2088711992.py:14: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(['-'], np.nan, inplace=True)

Total NaN after replacing '-':
Unnamed: 0             0
ts                     0
uid                    0
id.orig_h              0
id.orig_p              0
id.resp_h              0
id.resp_p              0
proto                  0
service          1434755
duration          900411
orig_bytes        900411
resp_bytes        900411
conn_state             0
local_orig       1446621
local_resp       1446621
missed_bytes           0
history             3786
orig_pkts              0
orig_ip_bytes          0
resp_pkts              0
resp_ip_bytes          0
label                  0
dtype: int64

Remove Outliers

In [ ]:
labels_to_remove = ['FileDownload']
df = df[~df['label'].isin(labels_to_remove)]
df['label'].value_counts()

label
PartOfAHorizontalPortScan    825939
Okiru                        262690
Benign                       199756
DDoS                         138777
C&C                           15531
Attack                         3915
Name: count, dtype: int64

One Hot Encoding

In [ ]:
#Perform One-Hot Encoding on proto and conn_state set as binary

df = pd.get_dummies(df, columns=['proto'],dtype=int)
df = pd.get_dummies(df, columns=['conn_state'],dtype=int)

In [ ]:
df.head()

,Unnamed: 0,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,service,duration,orig_bytes,...,conn_state_RSTOS0,conn_state_RSTR,conn_state_RSTRH,conn_state_S0,conn_state_S1,conn_state_S2,conn_state_S3,conn_state_SF,conn_state_SH,conn_state_SHR
0,0,1.525880e+09,CDe43c1PtgynajGI6,192.168.100.103,60905.0,131.174.215.147,23.0,NaN,2.998796,0,...,0,0,0,1,0,0,0,0,0,0
1,1,1.525880e+09,CJaDcG3MZzvf1YVYI4,192.168.100.103,44301.0,91.42.47.63,23.0,NaN,NaN,NaN,...,0,0,0,1,0,0,0,0,0,0
2,2,1.525880e+09,CMBrup3BLXivSp4Avc,192.168.100.103,50244.0,120.210.108.200,23.0,NaN,NaN,NaN,...,0,0,0,1,0,0,0,0,0,0
3,3,1.525880e+09,CfHl9r3XMYtDQRrHnh,192.168.100.103,34243.0,147.7.65.203,49560.0,NaN,2.998804,0,...,0,0,0,1,0,0,0,0,0,0
4,4,1.525880e+09,C7USrA15nFVkniMqC5,192.168.100.103,34840.0,145.164.35.6,21288.0,NaN,NaN,NaN,...,0,0,0,1,0,0,0,0,0,0

Removed Skewedness

In [ ]:
df.shape

(1446608, 36)

In [ ]:
numeric_cols = ['duration', 'orig_bytes', 'resp_bytes']

df[numeric_cols] = df[numeric_cols].replace('-', 0.0)

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0.0)

print(df[numeric_cols].dtypes)

duration      float64
orig_bytes    float64
resp_bytes    float64
dtype: object

In [ ]:
df = df[
    ~(
        (df['duration'] == 0) &
        (df['orig_bytes'] == 0) &
        (df['resp_bytes'] == 0) &
        (df['missed_bytes'] == 0) &
        (df['orig_pkts'] == 1) &
        (df['resp_pkts'] == 0) &
        (df['proto_tcp'] == 1) &
        (df['conn_state_S0'] == 1)
    )
]

mask = (
    (df['duration'] == 0) &
    (df['orig_bytes'] == 0) &
    (df['resp_bytes'] == 0) &
    (df['missed_bytes'] == 0) &
    (df['orig_pkts'] == 1) &
    (df['resp_pkts'] == 0) &
    (df['proto_tcp'] == 1) &
    (df['conn_state_S0'] == 1)
)

print("Rows removed:", mask.sum())
df = df[~mask]

Rows removed: 0

In [ ]:
df

,Unnamed: 0,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,service,duration,orig_bytes,...,conn_state_RSTOS0,conn_state_RSTR,conn_state_RSTRH,conn_state_S0,conn_state_S1,conn_state_S2,conn_state_S3,conn_state_SF,conn_state_SH,conn_state_SHR
0,0,1.525880e+09,CDe43c1PtgynajGI6,192.168.100.103,60905.0,131.174.215.147,23.0,0,2.998796,0.0,...,0,0,0,1,0,0,0,0,0,0
3,3,1.525880e+09,CfHl9r3XMYtDQRrHnh,192.168.100.103,34243.0,147.7.65.203,49560.0,0,2.998804,0.0,...,0,0,0,1,0,0,0,0,0,0
8,8,1.525880e+09,CFXxTW19F3sluNEkJk,192.168.100.103,52259.0,193.189.106.178,23.0,0,2.999300,0.0,...,0,0,0,1,0,0,0,0,0,0
9,9,1.525880e+09,CRRl9U39PzvL3OiS61,192.168.100.103,42207.0,10.169.219.98,8080.0,0,2.993548,0.0,...,0,0,0,1,0,0,0,0,0,0
11,11,1.525880e+09,Cx7t1f1wqRES8kiTq6,192.168.100.103,40459.0,212.110.180.188,23.0,0,2.998807,0.0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1446603,122,1.562165e+09,CbiAr234EfpzQInxbg,0.0.0.0,68.0,255.255.255.255,67.0,dhcp,90.034713,3300.0,...,0,0,0,1,0,0,0,0,0,0
1446604,123,1.562165e+09,CqEhZf1lYmVokqECn3,::,143.0,ff02::16,0.0,0,90.399970,340.0,...,0,0,0,0,0,0,0,0,0,0
1446605,124,1.562165e+09,Cr5vKO1CGfMQwFp22c,::,135.0,ff02::1:ffd5:cdf,136.0,0,89.824030,72.0,...,0,0,0,0,0,0,0,0,0,0
1446606,125,1.562165e+09,CQ5cJ21U9NUbUWIznd,fe80::5bcc:698e:39d5:cdf,143.0,ff02::16,0.0,0,45.215915,200.0,...,0,0,0,0,0,0,0,0,0,0
1446607,126,1.562165e+09,CjD5ve2qwxfFtvd4zl,fe80::5bcc:698e:39d5:cdf,133.0,ff02::2,134.0,0,44.242223,0.0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df.to_csv('IoT23Dataset.csv',index=False)

Feature Engineering

In [ ]:
df.shape

(1446608, 36)

In [ ]:
print(df.label.value_counts())

label
PartOfAHorizontalPortScan    825939
Okiru                        262690
Benign                       199756
DDoS                         138777
C&C                           15531
Attack                         3915
Name: count, dtype: int64

In [ ]:
#Connection Rate (Flows Per Second)
df['ts'] = pd.to_datetime(df['ts'], unit='s')
df = df.sort_values('ts')

# Set the index to timestamp for rolling window calculations
df = df.set_index('ts')

# Group by Source IP to analyze behavior per device
gb = df.groupby('id.orig_h')

# Feature A: Connection Rate (Flows per second)
df['conn_rate_1s'] = gb['uid'].rolling('1s').count().reset_index(0, drop=True)

# Feature B: Port Variety
df['unique_ports_1m'] = gb['id.resp_p'].rolling('60s').apply(lambda x: len(set(x))).reset_index(0, drop=True)

# Feature C: Inter-Arrival Time (IAT)
df['iat'] = gb.apply(lambda x: x.index.to_series().diff().dt.total_seconds()).reset_index(0, drop=True).fillna(0)

# Feature D: Average Packet Size (using ip_bytes for more detail)
df['avg_orig_pkt_size'] = df['orig_ip_bytes'] / (df['orig_pkts'] + 1e-5)

/tmp/ipython-input-2679806613.py:20: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df['iat'] = gb.apply(lambda x: x.index.to_series().diff().dt.total_seconds()).reset_index(0, drop=True).fillna(0)

Feature Selection - Drop Unnecessary Column

In [ ]:
print(df.columns)

Index(['Unnamed: 0', 'uid', 'id.orig_h', 'id.orig_p', 'id.resp_h', 'id.resp_p',
       'service', 'duration', 'orig_bytes', 'resp_bytes', 'local_orig',
       'local_resp', 'missed_bytes', 'history', 'orig_pkts', 'orig_ip_bytes',
       'resp_pkts', 'resp_ip_bytes', 'label', 'proto_icmp', 'proto_tcp',
       'proto_udp', 'conn_state_OTH', 'conn_state_REJ', 'conn_state_RSTO',
       'conn_state_RSTOS0', 'conn_state_RSTR', 'conn_state_RSTRH',
       'conn_state_S0', 'conn_state_S1', 'conn_state_S2', 'conn_state_S3',
       'conn_state_SF', 'conn_state_SH', 'conn_state_SHR', 'conn_rate_1s',
       'unique_ports_1m', 'iat', 'avg_orig_pkt_size'],
      dtype='object')

In [ ]:
df = df.drop(columns=['Unnamed: 0','uid','id.orig_h','id.orig_p','id.resp_h','id.resp_p',
                               'service','local_orig','local_resp','history'])

In [ ]:
print(df.columns)

Index(['duration', 'orig_bytes', 'resp_bytes', 'missed_bytes', 'orig_pkts',
       'orig_ip_bytes', 'resp_pkts', 'resp_ip_bytes', 'label', 'proto_icmp',
       'proto_tcp', 'proto_udp', 'conn_state_OTH', 'conn_state_REJ',
       'conn_state_RSTO', 'conn_state_RSTOS0', 'conn_state_RSTR',
       'conn_state_RSTRH', 'conn_state_S0', 'conn_state_S1', 'conn_state_S2',
       'conn_state_S3', 'conn_state_SF', 'conn_state_SH', 'conn_state_SHR',
       'conn_rate_1s', 'unique_ports_1m', 'iat', 'avg_orig_pkt_size'],
      dtype='object')

In [ ]:
df.head()

,duration,orig_bytes,resp_bytes,missed_bytes,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,label,proto_icmp,...,conn_state_S1,conn_state_S2,conn_state_S3,conn_state_SF,conn_state_SH,conn_state_SHR,conn_rate_1s,unique_ports_1m,iat,avg_orig_pkt_size
ts,,,,,,,,,,,,,,,,,,,,,
2018-05-09 15:30:31.015073061,0,0,0,0.0,1.0,40.0,0.0,0.0,Benign,0,...,0,0,0,0,0,0,1.0,1.0,0.000000,39.9996
2018-05-09 15:30:32.015492916,0,0,0,0.0,1.0,40.0,0.0,0.0,Benign,0,...,0,0,0,0,0,0,1.0,2.0,1.000420,39.9996
2018-05-09 15:30:32.016239882,2.998796,0,0,0.0,3.0,180.0,0.0,0.0,PartOfAHorizontalPortScan,0,...,0,0,0,0,0,0,2.0,3.0,0.000747,59.9998
2018-05-09 15:30:32.024985075,0,0,0,0.0,1.0,60.0,0.0,0.0,PartOfAHorizontalPortScan,0,...,0,0,0,0,0,0,3.0,3.0,0.008745,59.9994
2018-05-09 15:30:32.044975042,0,0,0,0.0,1.0,60.0,0.0,0.0,PartOfAHorizontalPortScan,0,...,0,0,0,0,0,0,4.0,3.0,0.019990,59.9994

In [ ]:
df.to_csv('IoT23CleanedFull.csv',index=False)

Percentage of Distribution for Each Class

In [ ]:
attackCount = df['label'].value_counts().reset_index()
attackCount.columns = ['label', 'Count']

TotalCount = attackCount['Count'].sum()
attackCount['Percentage'] = (attackCount['Count'] / TotalCount) * 100

print(attackCount)

                       label   Count  Percentage
0  PartOfAHorizontalPortScan  825939   57.111889
1                      Okiru  262690   18.164443
2                     Benign  199756   13.812694
3                       DDoS  138777    9.596128
4                        C&C   15100    1.044132
5                     Attack    3915    0.270714

In [ ]:
del attackCount

Undersampling the Major Class

In [ ]:
from sklearn.utils import resample

# Separate majority and minority classes
df_majority = df[df.label == 'PartOfAHorizontalPortScan']
df_minority = df[df.label != 'PartOfAHorizontalPortScan']

# Undersample majority class
df_majority_undersampled = resample(df_majority,
                                 replace=False,    # sample without replacement
                                 n_samples=300000, # to match desired number
                                 random_state=42) # reproducible results

# Combine minority class with undersampled majority class
df = pd.concat([df_majority_undersampled, df_minority])

# Display new class counts
print(df.label.value_counts())

label
PartOfAHorizontalPortScan    300000
Okiru                        262690
Benign                       199756
DDoS                         138777
C&C                           15531
Attack                         3915
Name: count, dtype: int64

In [ ]:
print(df.shape)

(920669, 23)

Percentage Distribution After Undersampling

In [ ]:
attackCount = df['label'].value_counts().reset_index()
attackCount.columns = ['label', 'Count']

TotalCount = attackCount['Count'].sum()
attackCount['Percentage'] = (attackCount['Count'] / TotalCount) * 100

print(attackCount)

                       label   Count  Percentage
0  PartOfAHorizontalPortScan  300000   32.585001
1                      Okiru  262690   28.532513
2                     Benign  199756   21.696831
3                       DDoS  138777   15.073495
4                        C&C   15531    1.686925
5                     Attack    3915    0.425234

In [ ]:
del attackCount

Saved to CSV files

In [ ]:
df.to_csv('IoT23CleanedUSam.csv',index=False)

Separate Each Class to a single csv files

In [ ]:
labels=df['label'].unique()

#Export each label to its own CSV
for label in labels:
  df_label = df[df['label'] == label]
  df_label.to_csv(f'{label}.csv', index=False)

  print(f"Saved {label}.csv")

Saved Benign.csv
Saved PartOfAHorizontalPortScan.csv
Saved C&C.csv
Saved Attack.csv
Saved Okiru.csv
Saved DDoS.csv

Feature Engineering

In [ ]:
import pandas as pd

file_path = '/content/drive/MyDrive/IoT23/IoT23Cleaned34USam.csv'


# Load the dataset into a pandas DataFrame
df = pd.read_csv(file_path)

print(f"Shape: {df.shape}")

Shape: (488093, 23)

In [ ]:
df['total_bytes'] = df['orig_bytes'] + df['resp_bytes']
df['total_pkts'] = df['orig_pkts'] + df['resp_pkts']

# Ratios and Rates
df['byte_rate'] = df['total_bytes'] / (df['duration'] + 1e-6)
df['pkt_rate'] = df['total_pkts'] / (df['duration'] + 1e-6)
df['avg_pkt_size'] = df['total_bytes'] / (df['total_pkts'] + 1e-6)

In [ ]:
df.head()

,duration,orig_bytes,resp_bytes,missed_bytes,orig_pkts,resp_pkts,label,proto_icmp,proto_tcp,proto_udp,...,conn_state_S2,conn_state_S3,conn_state_SF,conn_state_SH,conn_state_SHR,total_bytes,total_pkts,byte_rate,pkt_rate,avg_pkt_size
0,0.000002,0.0,0.0,0.0,2.0,0.0,PartOfAHorizontalPortScan,0,1,0,...,0,0,0,0,0,0.0,2.0,0.0,666666.666667,0.0
1,3.132217,0.0,0.0,0.0,6.0,0.0,PartOfAHorizontalPortScan,0,1,0,...,0,0,0,0,0,0.0,6.0,0.0,1.915575,0.0
2,0.000002,0.0,0.0,0.0,2.0,0.0,PartOfAHorizontalPortScan,0,1,0,...,0,0,0,0,0,0.0,2.0,0.0,666666.666667,0.0
3,0.000002,0.0,0.0,0.0,2.0,0.0,PartOfAHorizontalPortScan,0,1,0,...,0,0,0,0,0,0.0,2.0,0.0,666666.666667,0.0
4,0.000005,0.0,0.0,0.0,2.0,0.0,PartOfAHorizontalPortScan,0,1,0,...,0,0,0,0,0,0.0,2.0,0.0,333333.333333,0.0

In [ ]:
df.to_csv('IoT23Cleaned34USamFE.csv',index=False)